name: Cleanup Workflow Runs

on:
  push:
    paths:
      - ".github/workflows/cleanup-runs.yml"
  schedule:
    - cron: "0 * * * *" # Hourly
  workflow_dispatch: # Allow manual trigger

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Delete old runs
        run: |
          # List all completed runs (including manual ones) older than 120h and delete them
          gh run list --older-than 120h --limit 1000 --json databaseId -q '.[].databaseId' | xargs -r -I{} gh run delete {}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
